name: unix

on:
 workflow_dispatch:
  inputs:
    bool:
     type: boolean
     required: true
    

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

      
      - if: ${{ github.event.inputs.bool == 'true' }}
        name: ss
        run: |
          echo hello world
          
