name: unix

on:
 workflow_dispatch:
  inputs:
    bool:
     type: boolean
     required: true
    

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

      - name: run shell
        if: ${{ github.event.inputs.bool == 'true' }}
        run: |
          echo hello world
          
